### ISSUE TITLE
goのパッケージ管理ツールの変更

### ISSUE THREAD

**Issue by oshixtaku** [mock-mock/mockmock-meter#42]
# 概要
今まではHerokuのドキュメントのせいでなんとなくgovendor？の流れだったが、
よく見るとgolang標準の管理機能(go.mod, go.sum)が使えることが分かったので、
そちらへ変更したい。

# 対応
- govendorによるvendor.jsonの廃止。
- 「export GO111MODULE=on」を叩く
- go modコマンドによるgo.modファイル生成とgo buildによるgo.modのUpdateとgo.sumファイルの生成。
詳細は：https://mock-mock.slack.com/archives/CJMUP5WKS/p1562083797004800?thread_ts=1562020154.000500&cid=CJMUP5WKS

※go getについて
https://qiita.com/propella/items/e49bccc88f3cc2407745#%E3%83%87%E3%83%95%E3%82%A9%E3%83%AB%E3%83%88%E5%8B%95%E4%BD%9C

※GO111MODULEについて
https://text.baldanders.info/golang/go-module-aware-mode/

# 関連
vgoについてはよく調べてはいないが、多分サードパーティ製なので、
まずはGo標準の管理ツールを勉強するのが良いのでは？という押川個人意見。

# その他
とりあえず、PR出します。

**Comment by yasu-murata** [comment]
vgoをgo標準で取り込みつつアップデートしたのがgo modulesなので標準利用で問題なしです！
